# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqGcDEC1dpA_mUJEncUL4yF3NjnMfsNd

### 1. Setup Gemini API

To use the Gemini API, you'll need an API key. If you don't already have one, create a key in Google AI Studio (`https://aistudio.google.com/apps`).

In Colab, add the key to the secrets manager under the "🔑" icon in the left panel. Give it the name `GOOGLE_API_KEY`. Then, we'll install the necessary library and pass the key to the SDK:
"""

# Install the Google Generative AI library
!pip install -q -U google-generativeai

import google.generativeai as genai
from google.colab import userdata

# Configure the Gemini API with your API key
try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY') # Changed to use the valid secret name
    genai.configure(api_key=GOOGLE_API_KEY)
    print("Gemini API configured successfully.")
except userdata.SecretNotFoundError:
    print("Error: GOOGLE_API_KEY not found in Colab secrets. Please add it.")
except Exception as e:
    print(f"An error occurred during API configuration: {e}")

"""Now, let's initialize the Generative Model. We will use `gemini-1.5-flash` for this task, as it's efficient for text generation."""



"""### 2. Define Configurable Prompt and Collect User Inputs

First, we'll define a configurable prompt template that the LLM will use to generate the emails. This allows you to easily adjust the tone or specific instructions for the email generation.

Next, we'll gather the required information for the email generation. For a command-line-like experience in Colab, we'll use Python variables to store these inputs.

### 3. Generate Email with Gemini Model

Now, we'll format the `PROMPT_TEMPLATE` with the user-provided inputs and use the `gemini_model` to generate the email content. We will then print the generated email.
"""

# Format the prompt with user inputs
formatted_prompt = PROMPT_TEMPLATE.format(
    tax_filing_service=tax_filing_service,
    shareholder_info=shareholder_info,
    state_of_operation=state_of_operation,
    business_category=business_category,
    business_intro=business_intro
)

# Generate the email content using the Gemini model
try:
    response = gemini_model.generate_content(formatted_prompt)
    generated_email = response.text

    print("\n--- Generated Email ---\n")
    print(generated_email)
    print("\n-----------------------\n")
except Exception as e:
    print(f"Error generating email: {e}\nPlease ensure your GOOGLE_API_KEY is correctly set in Colab secrets and retry.")

# Configurable Prompt Template
# You can modify this prompt to change how the emails are generated.
PROMPT_TEMPLATE = """
You are an AI assistant tasked with drafting an email to a CPA firm to inquire about tax filing services for a C-Corporation.
Your goal is to get a quote and potentially set up a meeting.

Here is the information about the startup:
- Exact tax filing service needed: {tax_filing_service}
- Shareholder information: {shareholder_info}
- State of operation: {state_of_operation}
- Business category: {business_category}
- 1-Phrase business introduction: {business_intro}

Draft a professional email suitable for sending to a CPA firm. The email should:
1. Clearly state the purpose of the email: inquiring about C-Corp tax filing services.
2. Include the provided details about the startup.
3. Ask for a quote for the specified services, considering the budget if applicable (but do not mention the budget directly in this initial email).
4. Suggest scheduling a brief meeting to discuss specific requirements and pricing, especially if there are foreign shareholders, and mention your availability. Provide a placeholder for the meeting time (e.g., 'your earliest convenience' or 'next week').
5. Maintain a professional and concise tone.

Subject: Inquiry: C-Corporation Tax Filing Services - {business_intro}

Body of the email:
"""

# User Inputs
# Please fill in the following details for your startup:
# These variables simulate command-line inputs.

budget = "$2,000 - $3,000" # Example budget. This is for internal reference, not directly in the initial email.
tax_filing_service = "Federal and State C-Corp tax filing, including K-1s for investors."
shareholder_info = "We have both domestic and foreign shareholders (from Europe and Asia)."
state_of_operation = "Delaware (registered), New York (primary operation)"
business_category = "Software as a Service (SaaS) for small businesses, not containing sensible industries."
business_intro = "A B2B SaaS startup providing CRM solutions for small businesses."

print("Prompt template and input variables defined.")

# Initialize the Gemini model
gemini_model = genai.GenerativeModel('gemini-flash-latest')
print("Gemini model initialized: gemini-flash-latest")

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)